### PR TITLE
Per subject analysis

### PR DESCRIPTION
**Pull request by janfb**
this is the first step for issue #3. Please test it and comment below.

### CODE REVIEW

**Comment by janfb** [comment]
I now changed the script to do the analysis for a given list of subject IDs and a list for beta bands. 

My idea is that you then run the analysis for the bands you want to try and select the desired channels and or conditions later in matlab. Does that make sense for you? 

The results will be saved to file for every band separately. I wil use python dicts with string keys so that the data will be loaded as structs in matlab. Is that useful?

**Comment by bernadettevanwijk** [comment]
The frequency bands will be slightly different for each subject - also between ON and OFF conditions. I'd like to be able to specify them per subject and condition individually. Perhaps we could have as input: subject_list, channel_numbers, beta_bands, and conditions (list of 'ON' and 'OFF'). I would like to save the results for all of them in one large .mat file (so could e.g. make a dictionary and save that scipy.io.savemat) It's fine to do the computations for all channels but I would only like to save the results for the one I specified in channel_numbers.

**Comment by janfb** [comment]
OK, I get it. And you want to specify only a single channel per subject, right? If you want to look at multiple channels per subject you would need multiple entries for that subject in `subject_list`, correct?

**Comment by janfb** [comment]
@bernadettevanwijk please have a look and let me know whether this is useful.

**Comment by bernadettevanwijk** [comment]
Nice! Could we maybe also store information in measures about the condition and channel so I know where the values belong to? Yes, in case of multiple conditions or channels per subject I will just use additional entries in the input variables.

**Comment by janfb** [comment]
Do the relative paths work for you? 

Sure, I added the lists of subjects, channels and conditions as additional entries in the final dict. Or would you like the channel and condition saved on the subject level? Then it would probably make for sense to have subject-ids as first level keys in the dict and not the measures.

**Comment by bernadettevanwijk** [comment]
I need another ../ for the relevant paths to work:

save_folder = os.path.abspath(os.path.join('../../../', 'analysis_data'))
data_folder = os.path.abspath(os.path.join('../../../', 'data'))

I think it's probably better to save the channel and condition information at the subject level so there can't be any confusion where the data belong to. Subject-ids as first level sound ok, or maybe it's possible to create two more levels? For example: esr -> subject -> condition -> channel. But I don't know whether this is possible. I don't really mind how it's done as long as all the info is there :-)

**Comment by janfb** [comment]
if you run the script from the folder in the repository and have the data in a separate folder on the same level as the repository folder, then the path `../../`should be fine. 

I changed it to have the subject on the first level and then all the info for that subject in a dict: the three measures, the channel, condition and beta band. I think this is the least cluttered way of doing it.

**Comment by bernadettevanwijk** [comment]
Only now the results get overwritten when there are multiple entries per patient. For example in this input file:

[example2_input.mat.zip](https://github.com/janfb/dbs_data_analysis/files/2549818/example2_input.mat.zip)

**Comment by janfb** [comment]
this should do it, I think. Please test

**Comment by bernadettevanwijk** [comment]
Almost :)  
DF.STN_R01.OFF.[10, 20] is not a valid name in matlab so I can't read it. Maybe we could store the beta band frequency values as a variable instead of a name. For example
DF.STN_R01.OFF.betaband = [10 20];
DF.STN_R01.OFF.esr= [x1 x2];
DF.STN_R01.OFF.rdsr= [x1 x2];
DF.STN_R01.OFF.plv=[x1 x2];

**Comment by janfb** [comment]
I see what you mean. This should fix it, betaband is now a key in the last dict layer. However, with this setting, entries that are the same except for the beta band range would overwrite each other. 
As an alternative I suggest to change the format of the key to `betaband10_20` such that it is readable by matlab and different bands can be saved under one subject.

**Comment by bernadettevanwijk** [comment]
Perfect! Thanks a lot. I don't mind the frequency ranges being overwritten. I only need 1 per subject/channel/condition. And in case I'd like to try another frequency range I could save the result in a new file. Will continue to work on the manuscript now.

**Comment by janfb** [comment]
OK then I will merge this PR into the master branch.

**Pull request merged**
